trigger: none

variables: 
  backendstoragename: 'dibstorage'
  backendservicename: 'Dibyo_svp_new'

pool: MyAgentpools1

steps : 

- task: TerraformInstaller@1
  displayName: 'Install Latest Terraform'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: 'Terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: '$(backendservicename)'
    backendAzureRmStorageAccountName: '$(backendstoragename)'
    backendAzureRmContainerName: 'dibcontainer'
    backendAzureRmKey: 'newdib.tfstate'
    instructions: 'Do you want to run init? Approve to continue.'

- task: TerraformTask@5
  displayName: 'Terraform Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTask@5
  displayName : 'Terraformm plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Dibyo_svp_new'

