trigger: none

pool: MyAgentpools1

steps : 

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Dibyo_svp_new'
    backendAzureRmStorageAccountName: 'dibstorage'
    backendAzureRmContainerName: 'dibcontainer'
    backendAzureRmKey: 'newdib.tfstate'